module.exports = {
    CHECK_EMAIL_PROP: 'SELECT id FROM proprietari WHERE email = $1',
    CHECK_EMAIL_PROF: 'SELECT id FROM professionista WHERE email = $1',
    CHECK_EMAIL : 'SELECT id FROM professionista join proprietari on email WHERE email = $1',
    INSERT_PROP: 'INSERT INTO proprietari (nome,cognome, email, password) VALUES ($1, $2, $3, $4)',
    INSERT_PROF: 'INSERT INTO professionista (nome,cognome,zona, email, password) VALUES ($1, $2, $3, $4, $5)',
    FIND_PROP_EMAIL: 'SELECT * FROM proprietari WHERE email = $1',
    FIND_PROF_EMAIL: 'SELECT * FROM professionista WHERE email = $1',
  //  FIND_BY_EMAIL: 'SELECT id, nome, cognome, email, data_registrazione FROM professionista WHERE email = $1 UNION SELECT id, nome, cognome, zona, email, data_registrazione FROM proprietari WHERE email = $1 ',
    FIND_PROP_ID: 'SELECT id, nome, cognome, zona, email, data_registrazione FROM proprietari WHERE id = $1',
    FIND_PROF_ID: 'SELECT id, nome, cognome, email, data_registrazione FROM professionista WHERE id = $1',
   // FIND_BY_ID: 'SELECT id, nome, cognome, email, data_registrazione FROM professionista WHERE id = $1 UNION SELECT id, nome, cognome, zona, email, data_registrazione FROM proprietari WHERE id = $1 ',
    GET_CAT_PROF: `SELECT id, nome, zona, tipologia, tariffa , tipo_animale  FROM professionista as P join servizio on P.id = id_professionista where zona = $1 AND tipologia = $2 `,
    GET_CAT_PROF_ANIMAL: `SELECT id, nome, zona, tipologia, tariffa , tipo_animale  FROM professionista as P  join servizio on P.id = id_professionista where zona = $1 AND tipologia = $2 AND tipo_animale = $3`,
    GET_PROF_ID: `SELECT id, nome, cognome , data_registrazione  FROM professionista   where id = $1 `,
    GET_SERVIZI: 'SELECT id, tipologia, tariffa, zona, tipo_animale from servizio where id_professionista = $1',
    GET_RECENSIONI: 'SELECT valutazione,commento,data_creazione,data_fine,data_inizio,tipologia from recensione as R join prenotazione P on R.id = P.id_prenotazione join servizio S on P.id_servizio = S.id  where id_professionista = $1',
    GET_DISP : 'SELECT id,data_inizio,data_fine,is_disponibile from disponibilita where id_servizio = $1',
    CHECK_SERVICE_OWNERSHIP: `SELECT id FROM servizio WHERE id = $1 AND id_professionista = $2`,
    ADD_AVAILABILITY: ` INSERT INTO disponibilita (data_inizio, data_fine, id_servizio)  VALUES ($1, $2, $3)RETURNING id, data_inizio, data_fine, is_disponibile, id_servizio`,
    DELETE_AVAILABILITY: ` DELETE FROM disponibilita WHERE id = $1  AND id_servizio IN (SELECT id FROM servizio WHERE id_professionista = $2)RETURNING id  `,
    ADD_SERVICE: ` INSERT INTO servizio (tipologia, tariffa, tipo_animale, zona, id_professionista)  VALUES ($1, $2, $3, $4, $5) RETURNING id, tipologia, tariffa, tipo_animale, zona`,
    DELETE_SERVICE: `DELETE FROM servizio  WHERE id = $1 AND id_professionista = $2 RETURNING id`,
    GET_SERVICE_BY_ID: `SELECT S.id,  S.tipologia,S.tariffa, S.tipo_animale, S.zona,P.nome AS nome_professionista, P.cognome AS cognome_professionista FROM servizio S JOIN professionista P ON S.id_professionista = P.id WHERE S.id = $1 `
};